dotnet/jitutils

src/jit-dasm/jit-dasm.cs
src/jit-diff/jit-diff.cs

More specifically allows for use of a particular tool, and be default
is untagged (as --base and --diff's output is default tagged "base"
and "diff" respectivly.  --crossgen allows for directly placeing a
particular dasm file.  This functionality is used in the runtest script
to build up the dasm output.

Add --crossgen flag.

---

src/cijobs/project.json
src/jit-analyze/project.json
src/jit-dasm/project.json
src/jit-diff/project.json
src/packages/project.json

Changes needed project.json to point to the RTM meta-package.  Additionally adds ubuntu-16.4.

Update jitutils to use NETCore.App 1.0.0

---

src/jit-diff/jit-diff.cs

Change adds a bit of a better error message and fixes a initialization problem
when computing the next "tag" when the output directory is empty.

Remove null reference exception when no JIT_DASM_ROOT specified.

---

src/jit-diff/jit-diff.cs

This change fixes a bug on Windows where we were not finding an installed tool
due to the file extention.  We now us a globbing method to find the exe in a
platform independent way.

Find crossgen tool in a platform independent way.

---

src/cijobs/cijobs.cs
src/jit-analyze/jit-analyze.cs
src/jit-dasm/jit-dasm.cs
src/jit-diff/jit-diff.cs

Adds a guard and error message around commands to make a more graceful
experience when a tool isn't on the path.

Add try except around command creation/invocation.

---

README.md
build.cmd
build.sh
doc/getstarted.md
src/cijobs/project.json
src/jit-analyze/README.md
src/jit-analyze/project.json
src/jit-dasm/README.md
src/jit-dasm/project.json
src/jit-diff/README.md
src/jit-diff/project.json
wrapper.cmd
wrapper.sh

Moves all jit utils to a flat directory of portable apps with script wrappers for invocation.
Portable apps are DLLs that have only MSIL and are invoked with 'dotnet.exe'.  Moving portable apps allows us to share the dotnet framework and only include a single directory on the path but requires wrapper scripts to hide the dotnet <mytool>.dll <args> command line.

Portable apps

---

src/jit-dasm/jit-dasm.cs

When the flag was addied the expansion was left out.  This change addes it in the same way as the --base or --diff flag does.

Adds relative to full path expansion for '--crossgen' flag.

---

bootstrap.cmd
bootstrap.sh

The bootstrap scripts are meant to set the PATH to include the path to the
jitutils executables. However, the way the export/set commands are
written, we attempt to add the actual executable to the path, rather than
the path to the executable ($root/jitutils/bin/jit-diff instead of
$root/jitutils/bin). This change updates the command so that when the user
runs the bootstrap scripts, the correct path is added to PATH, and the
user can just run the utilities without using their full path name.

Fix path setting in bootstrap scripts

---

src/jit-analyze/jit-analyze.cs

Jit diffs are unable to disambiguate some kinds of overloads because types
are mapped into a simplified set (ref, struct, etc). This can make
interpreting the total bytes of diff per method a bit tricky since the
entry may represent the total change from a set of methods. So, report on
how many folded overloads there are in the BASE set.
Example:
```
Top method improvements by size (bytes):
-2801 : System.Private.CoreLib.dasm - System.Array:LastIndexOf(ref,struct,int,int):int (9 methods)
-2328 : System.Private.CoreLib.dasm - System.Array:Sort(ref,int,int,ref) (25 methods)
```

Add approximate overload counts to the "top N" methods lists

---

src/jit-format/jit-format.cs

We decided to go with SOURCE_FORMATTING in the include files to allow
clang to parse coreclr.

Add -DSOURCE_FORMATTTING to compile_commands.json

---

bootstrap.cmd
bootstrap.sh

This change updates boostrap.cmd/sh to install clang-format/clang-tidy
if they are not currently on the PATH. We then check the version of the
tools that are installed to confirm that version 3.8.* is installed. If
the wrong version is installed, boostrap.cmd/sh will inform the user
that jit-format requires 3.8.*, and will direct them to LLVM.org to
install the appropriate version.
We currently have downloads of the tools on Azure blob storage for
Ubuntu 14.04, Ubuntu 16.04, OSX, CentOS, and Windows. On other operating
systems, we direct the user to LLVM.org to install the appropriate
version for their platform.

Download clang-format/clang-tidy if not on PATH

---

bootstrap.cmd
bootstrap.sh
src/jit-format/jit-format.cs

I assumed that coreclr built into the name of the operating system on
various flavors of Linux, but it turns out they are built into
Linux.<arch>.<build>. This change fixes SetPlatform to set the OS as
Linux if the OS reported by dotnet --info is not Windows or OSX.
Additionally, in bootstrap, we were trying to get the exes which do
not exist for Linux platforms (they do not have extensions). This
change fixes the wget, and makes the files executable. It also only
checks the version if the tools were already on the path.

Fix SetPlatform() and bootstrap for Linux platforms

---

src/cijobs/cijobs.cs
src/jit-diff/jit-diff.cs

Fixes some usability bugs on Linux that showed up in daily use.
- Fix format string in cijobs that cropped up from Ian's change.
- Fix issue with installing tools on Linux where we weren't defaulting to the right string to find the product tools folder downloaded from the coreclr build.
- Check paths that are used in default base/diff so as to provide a more graceful error message.

Add more robust platform detection and checking of defaults

---

src/jit-format/jit-format.cs

I missed one spot where we referenced _buildLog, which has been removed.
This fixes the build issue.

Fix build log issue

---

bootstrap.cmd
bootstrap.sh

Bootstrap.sh calls validate_url, whose definition had parentheses. This
was not legal in the lab, so this change removes those parentheses.
Additionally, for the lab we need to install the 3.8 clang tools if they
are not yet installed. This change will download 3.8 if another version
of the tools is already installed.

Fix bugs in boostrap

---

doc/getstarted.md

We have introduced a formatting python script for the lab that can also
be run locally that devs can use to format the jit directory. Update the
documentation to call it out.

Update documentation for jit-format

---

src/jit-format/jit-format.cs

If the obj\<os>.arch.build directory does not exist, we need to create
it or we will get a StackOverflowException. This should only happen on
Windows, as cmake will build into nmakeobj, not obj. CreateDirectory
will create the directory if it does not exist, and do nothing if the
directory already exists.

Create compile_commands directory if it doesn't exist

---

bootstrap.sh

The back quotes for validate_url and the grep command were wrong for the
version of bash on our linux machines. Additionally, this change moves
the tools download to a function so we can call it both if we don't have
the tools installed and if we have the wrong version installed.

Fix validate_url for bash and move tools download to function

---

README.md
doc/getstarted.md
src/jit-dasm/jit-dasm.cs
src/jit-diff/jit-diff.cs
wrapper.cmd

This change moves all of the diff logic to jit-diff, which will invoke
jit-dasm once for each tag.
jit-dasm now takes an argument that specifies the crossgen executable to
use, and an optional jit argument that will be passed along to crossgen
via /JITPath.
jit-diff has been modified to take an additional argument that specifies
the crossgen executable to use. With this argument, jit-diff will use
clrjit from the the --base and --diff arguments (which are now
directories instead of the full crossgen path) with the specified
crossgen. This should prevent changes to
System.Private.CoreLib.dll (which must match the crossgen version) from
manifesting as jit diffs.

Factor diff logic, add support for --crossgen flag

---

bootstrap.cmd

If they've already been downloaded to the 'bin' directory, where
we download them, then don't download them again.

Avoid downloading clang-format and clang-tidy

---

src/jit-format/jit-format.cs

We don't want to message about missing JIT_UTILS_ROOT. Instead, we will
message when we find a JIT_UTILS_ROOT and inform the user that a
configuration was loaded.

Don't print message about missing JIT_UTILS_ROOT

---

src/jit-format/jit-format.cs

Fix and untidy require two dashes.

Fix output when formatting errors found

---

src/jit-format/jit-format.cs

We need better error messages/handling in jit-format. This change
updates the following error scenarios:
1) The specified coreclr path does not exist or is not a wellformed
coreclr repo. We chech to make sure that both the directory exists, and
that build.cmd and build.sh exist within the specified directory.
2) jit-format was cancelled mid-run, specifically before the clang-tidy
step has a chance to delete the newCompileCommands file. We now check to
see if newCompileCommands already exists, and delete it before trying to
move the full compileCommands database to that file. File.Delete will do
nothing if the file does not exist.
Fixes #63.
Fixes #64.

Fix error messages for various scenarios in jit-format

---

doc/getstarted.md
src/jit-diff/jit-diff.cs

This change fixes [67](https://github.com/dotnet/jitutils/issues/67) and [68](https://github.com/dotnet/jitutils/issues/68).
Instead of using pattern matching to find clrjit and crossgen, we now look for the exact names of these binaries: libclrjit.so/crossgen on linux, and clrjit.dll/crossgen.exe on windows.
The documentation update reminds the user to use the platform-specific crossgen executable name.

Look for exact name of clrjit and crossgen

---

src/cijobs/project.json
src/jit-analyze/project.json
src/jit-dasm/jit-dasm.cs
src/jit-dasm/project.json

Also fix dependency versions to be consistent between tools and add
version numbers used to publish packages for the coreclr jitdiff jobs

Don't emit error files from jit-dasm for non-managed assemblies

---

src/jit-format/project.json

Jit-format was running into issues after a change in the dependency
versions of other jitutils tools.
Because we publish all of the jitutils tools into a common directory,
the dependencies of the last package to get published will end up in
the publish directory. Eventually we should fix this behavior, but for
now modifying jit-format to use the same dependency versions as cijobs
works around the issue.
@adiaaida @russellhadley

Make jit-format use the same version of packages as the other tools

---

src/jit-analyze/jit-analyze.cs
src/jit-dasm/jit-dasm.cs
src/jit-diff/jit-diff.cs
src/jit-format/jit-format.cs

The `DefaultCommandResolverPolicy` includes a `ProjectToolsCommandResolver`
which chokes if it finds multiple project files, so e.g. running jit-diff
from the root coreclr directory currently fails.  Update all the calls to
`Command.Create` to instead use `ScriptCommandResolverPolicy` via a local
wrapper class to proxy the interface call to the static `Create` method.

Use ScriptCommandResolverPolicy

---

doc/getstarted.md

Point out that we require a csproj-compatible version of the dotnet cli
tools.

Update getstarted.md with cli version info

---

src/jit-dasm/jit-dasm.cs

Update jit-disasm to delete the .ni.exe/dll files it creates, to make sure
they don't unintentionally get picked up by subsequent test runs in the
same test tree.
Resolves #74

Clean up generated native files

---

src/jit-analyze/jit-analyze.cs

`StartsWith` defaults to `StringComparison.CurrentCulture` but that is slow and we don't really need it here, quite the contrary. Use `StringComparison.Ordinal` instead, it's 2 times faster.
`ExtractFileInfo` time drops from ~4s to ~2s on my machine when the input files are in the filesystem cache.

Speed up jit-analyze's ExtractMethodInfo

---

build.cmd
build.sh
src/packages/packages.csproj

In the migration to csproj, the frameworks-populating of `build -f` was
lost, because packages.csproj can't specify standalone like project.json
could.  With csproj, an explicit --runtime argument must be passed to
dotnet restore in order to publish as a standalone.  The dotnet publish
--runtime in turn requires that the project has been restored for the
specified runtime, so add an explicit `dotnet restore --runtime` in the
build scripts when processing -f.

Fix `build -f`

---

src/jit-format/jit-format.cs

Helps protect against the unfortunately-common occurrence of inability to
build coreclr from a directory other than the root.

Make jit-format run build from coreclr-root

---

src/jit-diff/jit-diff.cs

If an asm run fails, e.g., in the baseline run, we were
immediately exiting. Instead, run all the baseline, diff,
and analyze tasks, so you can get as much information as
possible from the code you've got.

Finish all diff tasks; don't exit early on failure

---

bootstrap.cmd
bootstrap.sh

If bootstrap.sh is invoked from the jitutils repo root directory,
then the build is done in the existing repo. Otherwise, the jitutils
repo is cloned and then built.

Fix bootstrap.sh to only clone jitutils when necessary

---

src/jit-dasm/jit-dasm.cs
src/jit-diff/jit-diff.cs

I reordered running diffs so base and diff of a single assembly are done back-to-back, so you can do diffs while the rest of the assemblies continue to be worked on.
The parallel work is in progress.
Any comments/suggestions?

Update jit-diff operation order, and parallelize

---

src/jit-dasm/jit-dasm.cs

This allows base/diff generated dasm files to be identical,
even if the .ni.dll was generated to different paths.

Pass /silent to crossgen

---

README.md
doc/cijobs.md
doc/diffs.md
doc/formatting.md

Split out README into separate files: (1) Assembly diffs
(jit-diff, jit-dasm, jit-analyze), (2) CI information (cijobs),
and (3) JIT code formatting (jit-format).

Simplify and clean up README

---

src/cijobs/cijobs.cs

The default of 100 seconds is often too short.  Set it to infinite, so
user or automation harness can control how long to wait before killing.

Suppress cijobs copy timeout

---

doc/diffs.md
src/jit-diff/diff.cs
src/jit-diff/jit-diff.cs

When --crossgen is not explicitly passed, pull it from --core_root rather
than --base or --diff; --crossgen and --core_root need to agree in build
flavor, but --base and --diff do not need to agree with them, so the
defaults of release --core_root and checked --base/--diff result in an
error otherwise.  This also helps ensure that crossgen.exe runs on the
corelib right next to it.

Use crossgen.exe from core_root

---

src/jit-diff/diff.cs
src/jit-diff/jit-diff.csproj

This gives a quick indication of whether diffs failed more with one jit
than the other.

Separate base/diff/exception dasm error counts

---

src/cijobs/cijobs.csproj
src/jit-analyze/jit-analyze.csproj
src/jit-dasm/jit-dasm.csproj
src/jit-diff/jit-diff.csproj
src/jit-format/jit-format.cs
src/jit-format/jit-format.csproj
src/packages/packages.csproj

Adds a `<TargetFrameworks>` element to each project that includes
netcoreapp2.0 as a target. This is useful because it makes it possible
to build and run jitutils with a 2.0 install of the cli, which doesn't
come with a 1.0 runtime.
For now, the default target is still netcoreapp1.0, to prevent
breaking ci jobs that run jitutils with a 1.0 runtime.

Support netcoreapp2.0

---

src/jit-diff/jit-diff.csproj

netcoreapp2.0 includes System.ValueTuple, so the extra
PackageReference was causing problems.

Condition ValueTuple reference on target framework

---

src/coreclr_config_download/README.md
src/coreclr_config_download/coreclr_config_download.py

This will allow the coreclr xml files to be diffed. Note that
there is some timing that requires the ci generate job to have
run.
@RussKeldorph @mmitche ptal
The only issue this seems to have is every Http request requires an OAuth to Github which after 2k+ authenticated get requests I seem to be blocked by Github to authenticate further.
This keeps the script from finishing and requires you to wait about 30 minutes before continuing.

Add scripting to download xml config files.

---

build.cmd
build.sh
doc/diffs.md
src/cijobs/cijobs.csproj
src/jit-analyze/jit-analyze.csproj
src/jit-dasm/jit-dasm.csproj
src/jit-diff/jit-diff.csproj
src/jit-format/jit-format.csproj
src/packages/packages.csproj

Since a few people have hit problems when trying to use jitutils with a 2.0 dotnet install, I think it's time to address https://github.com/dotnet/jitutils/issues/116.
With this change, you'll need to install the 2.0 dotnet SDK to build jitutils.
@adiaaida, I think at some point the jit-format jobs were building jitutils using some specific version of the SDK. This might require the format jobs to be updated if they still do that.
/cc @sandreenko

Target netcoreapp2.0 by default

---

src/jit-analyze/jit-analyze.cs

When multiple same-named methods exist in different numbers in base and
diff, make it clearer in the output. Also call out methods that are exclusive
to base or diff.
Allow analysis to skip reconciliation; this option is useful when
the larger diffs are all in unique methods and you want to focus in on the
methods that are common.

Show when number of methods differs in base/diff

---

src/jit-dasm/jit-dasm.cs

Avoids spurious diffs that sometimes appear when errors occur (sometimes the logo lines and error lines are interleaved).
For example:
```diff
--- D:\Projects\diffs\dasmset_6\base\JIT\jit64\eh\FinallyExec\nonlocalgotoinatryblockinahandler\nonlocalgotoinatryblockinahandler.err	2017-11-30 21:03:30.000000000 +-0200
+++ D:\Projects\diffs\dasmset_6\diff\JIT\jit64\eh\FinallyExec\nonlocalgotoinatryblockinahandler\nonlocalgotoinatryblockinahandler.err	2017-11-30 21:03:30.000000000 +-0200
@@ -1,5 +1,5 @@
Microsoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0
-Copyright (c) Microsoft Corporation.  All rights reserved.
Error: Could not load file or assembly 'common, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified. (Exception from HRESULT: …
```

Pass /nologo to crossgen

---

src/pmi/PMI.csproj
src/pmi/pmi.cs

This change adds the ability for PMI to create instantations of some
generic types (limited to types with one or two parameters only for now).
Because of constraints it is not possible to easily tell in advance how
many instantations will result. Also in the future we will want to do
something similar for generic methods, and may want to produce different
kinds of output markup.
So this change also refactors the PMI code to use a visitor pattern for
traversing types and methods. Three concrete visitors are implemented:
one for counting types and methods, one for jitting a range of methods, and
one for jitting just a single method.
The actual strategy for instantiating generics is held in the `Worker` class.
We attempt up to 4 instantations of single parameter types and 8 of two
parameter …

PMI: rework as visitor pattern to support generic type exploration

---

src/pmi/pmi.cs

The -QUIET suffix now produces just one output line per assembly with no timing
data. It is intended for use by upstack tools like `jit-diffs` to reduce the
volume of diff text and reduce spurious diffs caused by PMI messages.
Add a new -TIME suffix to print per-assembly times, even in -quiet mode. This
is useful when using PMI as a jit throughput tool.

pmi: add -TIME option and make -QUIET mode more quiet

---

src/jit-analyze/jit-analyze.cs
src/jit-dasm-pmi/jit-dasm-pmi.cs
src/jit-diff/diff.cs
src/jit-diff/jit-diff.cs
src/pmi/pmi.cs

Have `jit-diff` pass a description string down to `jit-analyze` so the
summary can describe what was being diffed. Capture the arch that was
actually used and add it to the description.
Have `jit-analyze` accept that description string and display it in the
summary.
Remove a diagnostic "adding" message inadvertenly left in `jit-analyze`'s
processing of files with text diffs.
Don't show final file diff (but no size diff) message in the analysis
summary if there were no such files (which is commonly the case).
Update Usage for `pmi` to indicate you must pass `pmi.dll` as the first arg
to your launcher if you launched via `dotnet` or `corerun`. This should
partially address #140.
Add a bit more EH to `jit-dasm-pmi` in a attempt to reduce the volume of
dotnet failure popup dialogs (seen when …

Some minor usability tweaks in jitutils

---

src/jit-dasm-pmi/jit-dasm-pmi.cs
src/jit-diff/diff.cs

When using altjit, don't print the SIMD message by default.
Base runs are the last set when there aren't any diff runs.

Fix a couple of quirks with status bar

---

src/jit-dasm-pmi/jit-dasm-pmi.cs
src/jit-dasm/jit-dasm.cs
src/jit-diff/diff.cs
src/jit-diff/jit-diff.cs

1. Show base/diff paths so you can copy/paste to a diff program
2. In verbose, display all environment variables set
3. Make all "-Using" output copy/paste friendly
4. Remove empty "After setting defaults" lines
5. In verbose, change progress bar to only display when a change has
occurred in the number of base or diff tasks completed.

Several improvements to diff output

---

src/jit-diff/diff.cs
src/jit-diff/jit-diff.cs

The path to BenchI and BenchF has changed, so only BenchmarksGame was being used with the --benchmarks option.
Also, I like to have the tsv file generated, and would prefer to save having the extra analyze step, so add that as a pass-through option.

Add More Benchmarks and Tsv option

---

src/jit-analyze/README.md
src/jit-analyze/jit-analyze.cs
src/jit-dasm-pmi/jit-dasm-pmi.cs

Turn off tiering by default for when invoking PMI. Can enable via -tiering.
Also, fix a couple of spelling errors.

jit-pmi-diff: disable tiering by default

---

src/pmi/pmi.cs

The logic to check for generic parameter type constraints was wrong.
If the constraint it itself generic then just skip checking and let
the runtime figure it out.
Handle the other classes of special constraint. Fix the check for the
class/interface constraint.
Add `long` to the types we try and use for instantiations since it
stresses x86.

PMI: Improve constraint checking logic

---

src/pmi/pmi.cs

Also fix issue instantiating two-parameter generic types where we
would only ever try the last suggested type for the second type param.
Also fix accounting for instantiated types and methods.

PMI: instantiate generic methods

---

src/jit-analyze/jit-analyze.cs

Isn't LINQ nice when re-evaluating a query results in re-reading gigabytes of data from disk?

Avoid re-reading .dasm files

---

src/pmi/pmi.cs

This seems to be sufficient to prevent JIT output corruption by the finalizer thread triggering a finalizer method compilation (e.g. such as in https://github.com/dotnet/jitutils/issues/164). Tested on Linux/arm Linux/x64 by pmi-ing S.P.C.dll
@mikedn @AndyAyersMS @BruceForstall PTAL
If the problem comes back would also try @mikedn's NoGCRegion suggestion  https://github.com/dotnet/jitutils/issues/164#issuecomment-416826491
/cc @dotnet/jit-contrib

Call GC.WaitForPendingFinalizer before PrepareMethod

---

src/jit-dasm-pmi/jit-dasm-pmi.cs
src/jit-dasm/jit-dasm.cs
src/jit-diff/diff.cs
src/jit-diff/jit-diff.cs

Off by default. Enable via --debuginfo.
Info is dumped after the method (like unwind and eh) and will show up
as file diffs.

Add option to dump debug info to jit-diffs

---

src/jit-dasm-pmi/jit-dasm-pmi.cs
src/jit-dasm/jit-dasm.cs

Relying on stdout redirection is not very efficient. The output is piped through jit-dasm rather than being written directly to the file and jit-dasm ends up consuming a lot of CPU. Also, the JIT disables stdio buffering when writing to the stdout and that makes things even slower.
Fixes #161

Use COMPlus_JitStdOutFile to speed-up disassembly

---

src/jit-analyze/jit-analyze.cs

This makes it much easier to find a small function with big impact
to analyze further, as opposed to looking at a large impact in a
very large function.
Also added percentage difference to the improved/regressed function
output for the functions ordered purely by size.
Sample percentage output:
```
Top method regressions by size (percentage):
17 (13.08% of base) : System.Data.Common.dasm - DataColumnCollection:FinishInitCollection():this
25 (13.02% of base) : Microsoft.DotNet.ProjectModel.dasm - FrameworkReferenceResolver:GetFrameworkInformation(ref):ref:this
32 (12.60% of base) : Microsoft.Diagnostics.Tracing.TraceEvent.dasm - DirectoryUtilities:Clean(ref):int
33 ( 8.55% of base) : System.Private.DataContractSerialization.dasm - XmlDictionaryReader:ReadContentAs(ref,ref):ref:this
20 ( …
```

jit-analyze: add percentage improved/regressed display for functions

---

src/jit-diff/diff.cs
src/jit-diff/jit-diff.cs

Two changes:
1. Allow you to specify multiple `--assembly` arguments; diffs will happen
for each specified assembly.
2. Allow an argument to `--assembly` to be a directory. In this case,
the directory tree will be searched for assemblies to diff.
E.g.,
```
jit-diff diff --pmi --base --diff --base_root f:\gh\coreclr12 --arch x64 --build Checked --assembly F:\gh\coreclr10\bin\tests\Windows_NT.x64.Release\JIT\jit64\localloc --assembly F:\gh\coreclr10\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\System.Collections.dll --assembly F:\gh\coreclr10\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\System.Collections.Specialized.dll
```

Extend jit-diff `--assembly` argument

---

src/jit-dasm-pmi/jit-dasm-pmi.cs
src/jit-dasm/jit-dasm.cs

We don't want to allow JIT fallback to MinOpts when generating
asm diffs.

Set environment variables to assert on NO_WAY and noway_assert

---

src/jit-dasm-pmi/jit-dasm-pmi.cs
src/jit-diff/diff.cs
src/jit-diff/jit-diff.cs
src/pmi/pmi.cs

Jit codegen can sometimes incorporate the values of initonly static fields.
These codegen diffs aren't usually visible to PMI as we haven't actually
initialized many classes.
Add an option to run class constructors for each discovered type to make it
more likely initonly static field values will be seen by the jit. Note cross-class
static accesses may or may not be picked up by this; we don't do anything clever
with the order of class initialization.
Closes #183.

Add support for cctors mode to jit-diffs, jit-dasm-pmi, pmi

---

build.cmd
build.sh
jitutils.sln
src/cijobs/cijobs.csproj
src/common.props
src/jit-analyze/jit-analyze.csproj
src/jit-dasm-pmi/jit-dasm-pmi.csproj
src/jit-dasm/jit-dasm.csproj
src/jit-diff/jit-diff.csproj
src/jit-format/jit-format.csproj
src/jit-include.props
src/packages/packages.csproj
src/pmi/pmi.csproj
src/target-framework.props

This change is based on #181 and adds these commits:
18d9a56: Use netcoreapp3.0 if available.
Allows to run [dotnet/performanc](https://github.com/dotnet/performancee) and arm64 (they both require 3.0 to be installed).
13050c6: Force the new project system for *.cs projects.
Otherwise it does not see `TargetFramework` from the props file and uses the old one that doesn't show *.cs files in VS (because that are not included by default in the old version), but it also doesn't allow to include them because then you will hit build errors (one file is included twice).
See the issue description dotnet/project-system#1358 and the workaround is at the end of the thread.
e5f39ab: Separate common.props into two files.
One defines `<TargetFramework>`, the other `<PackageReference Include>`.
This …

Use net core app3 if available

---

src/pmi/PMIDriver.cs
src/pmi/pmi.cs

NETCOREAPP2_1 does not imply NETCOREAPP3_0. We can clean all this up
once NETSTANDARD2_1 becomes a thing.

Fix some ifdefs so pmi works with 3.0

---

src/jit-dasm-pmi/jit-dasm-pmi.cs

Currently PMIPATH is always set to an empty string. It should be set to the
directory of the target assembly.
Closes #201.

jit-dasm-pmi: set PMIPATH properly

---

NuGet.Config

Linux/arm64 PMI asm diffs (using 3.0 dotnet CLI) would fail to
restore without this.

Add new NuGet package source

---

src/jit-format/jit-format.cs

Right now the fact that jit-format needs a compile_commands.json file isn't explicit anywhere in CoreCLR and nowhere in CoreCLR uses the compilation database. This change makes jit-format explicitly request the compile_commands.json on Unix systems where there is a `-cmakeargs` parameter to our build scripts.
There's no comparable flag on our Windows build scripts, so there's not a good way to move that knowledge into jit-format. As a result, I'm planning a PR into CoreCLR that will only tell CMake to generate a compile_commands.json when the `usenmakemakefiles` parameter is passed (which makes sense because the only reason to use the NMake generator is to generate a compile_commands.json file since the VS generators don't support generating a compile_commands.json).

Have jit-format explicitly specify that it needs a compile_commands.json from the CMake configuration

---

src/pmi/pmi.cs

Tweak the `CustomLoadContext` we define for pre-netcoreapp 3.0 builds.

Fix PMI for 2.x SDKs

---

src/mutate-test/Program.cs
src/mutate-test/mutate-test.csproj

The MutateTest tool takes existing test cases and adds various syntactic
mutations that alter the program expression and execution without altering
the computed results. The aim is to extend the usefulness of existing tests
and to stress the jit in novel ways, for instance, introducing EH constructs
into methods.
Mutation is done at the syntax tree level. There is a suite of basic mutations
and a number of compositional operators to combine or alternate mutations. For
example a block can be wrapped in the try of a try/catch, the try of a
try/finally, the catch of a try/catch where the try throws an exception that
gets caught, and so on.
Some care must be taken when blocks are moved into finallys or catches because
execution of blocks in these contexts can require considerably more stack. …

MutateTest: experimental tool to mutate existing test cases

---

src/jit-format/jit-format.cs

1. Don't add the precompiled header option.
2. Pass -D_ALLOW_COMPILER_AND_STL_VERSION_MISMATCH so that older versions of clang-tidy.exe work in VS2019 environment.

More fixes for jit-format.

---

src/jit-include.props
src/target-framework.props

Force targetting netcoreapp3.0 unless we are actually on netcoreapp2.1.
(Maybe 2.1 support should be removed entirely?)

Enable jitutils build with .NET Core 5.0 SDK installed

---

src/jit-analyze/jit-analyze.cs
src/jit-diff/diff.cs
src/jit-diff/jit-diff.cs

Alternative take to #215 where jit-analyze is updated to look for
and process multiple bits of metric data.
With the pattern shown here it should be simple to add additional
metrics like the ones we already have.

Update jit-analyze to handle multiple metrics

---

bootstrap.cmd
bootstrap.sh
build.cmd
build.sh
eng/build.yml

Update the build process to pay attention to failures, and fail the CI on failures.
Also, update AzDO to use 3.x including preview builds. Currently, this means 3.1.100-preview2-014569.

Update jitutils build process to pay attention to failures

---

src/jit-analyze/jit-analyze.cs

Ensure a tab before each "Base" metric,
and add a space before metric name to make it easier to view in excel (with wrap text)

Fix header for diff tsv file

---

src/jit-format/jit-format.cs

@dotnet/jit-contrib ptal
This change is updating format job to use `/artifacts` in place of `/bin`. https://github.com/dotnet/runtime/pull/51 for the change

Use /artifacts in place of /bin

---

doc/diffs.md
src/jit-dasm/jit-dasm.cs
src/jit-diff/jit-diff.cs

--crossgen arg can now point to crossgen.exe or crossgen2.exe.
crossgen.exe and crossgen2.exe have diffferent command line args
so jit-dasm takes care of passing the right args depending on whether
--crossgen points to crossgen.exe or crossgen2.exe.

Add support for crossgen2 to jit-dasm and jit-diff.

---

src/pmi/pmi.cs

It's possible for timer to be null when the callback fires. I saw
this a few times when gathering `--tier0` diffs via `jit-diffs`.

PMI: fix race condition in timer callback

---

src/jit-dasm/jit-dasm.cs

This is a follow-up to #228. Unlike crossgen.exe, crossgen2.exe
needs an explicit --optimize option. I added the method to set it
in #228 but forgot to call it from GenerateAsm. This change adds
the missing call.

Add --optimize option to calls to crossgen2.exe.

---

src/jit-analyze/jit-analyze.cs

I have changed the JIT to always use the term PerfScore everyplace.
This updates the regex to match either "perf score" or "PerfScore"

Allow both "perf score" and "PerfScore" is the Disassembly output

---

build.cmd
build.sh
doc/diffs.md
src/jit-format/jit-format.cs
src/jit-include.props
src/mutate-test/mutate-test.csproj
src/pmi/pmi.csproj
src/target-framework.props

- Move from 3.0 to 3.1
- If 5.0 is installed, use that
- Stop building obsolete cijobs (I didn't want to delete it just yet; maybe
it could be repurposed for AzDO?)

Update jitutils .NET Core SDK references

---

src/jit-analyze/jit-analyze.cs

1. MetricCollection.metrics was omitted by Json serializer since
it's private. The fix is to apply JsonProperty atribute to it.
2. Calling JsonConvert.SerializeObject on each file info was resulting
in an invalid json file. The fix is to call it on a filtered list of
file infos.

Fix --json jit-analyze option.

---

src/jit-diff/jit-diff.cs
src/jit-format/README.md
src/jit-format/jit-format.cs
src/util/util.cs

This resolves https://github.com/dotnet/jitutils/issues/230 ~~https://github.com/dotnet/jitutils/issues/243~~
This does not provide any switch to continue working on dotnet/coreclr, as I assume there wont be any significant changes and devs needing to test changes can always use an older snapshot of jitutils (such as commit 7e6c68b913c3b0a06821ae77a184d681d3ecefc6 or prior).

Fixup jitutils to work with the dotnet/runtime repo

---

src/jit-analyze/jit-analyze.cs

Delta is always diff - base. So we need to subtract base and add diff;
I had it reversed.

Fix reconciliation math in PMI

---

src/jit-dasm-pmi/jit-dasm-pmi.cs
src/pmi/PMIDriver.cs
src/pmi/pmi.cs

PMI in DRIVEALL mode invokes subprocesses in PREPALL mode
in order to be able to recover from errors. We had COMPlus environment
variables (including COMPlus_JitStdOutFile) set for both the parent and
child processes so the jit emitted disassembly, etc. to the same file.
The parent process was still active when the child was running (e.g.,
it called p.StandardOutput.ReadToEnd()). That resulted in duplicate
methods (especially from System.Private.Corelib) in the dasm file and
non-deterministic output interleaving.
The fix is not to set the COMPlus environment variables  in jit-dasm-pmi
when invoking pmi but instead pass them in PMIENV environment variable
as semicolon-separated name=value pairs and set the actual COMPlus
environment variables only on child processes.
I also fixed a …

Fix PMI non-determinism and a potential deadlock.

---

src/pmi/pmi.cs

1. The timer workaround is no longer needed since EventPipe file polling
was removed in https://github.com/dotnet/coreclr/pull/24225
2. https://github.com/dotnet/runtime/pull/467 introduced a change that
causes pmi non-determinism.
System.Threading.Thread.s_isProcessorNumberReallyFast can have different
values on two invocations of the process on the same machine.
(https://github.com/dotnet/runtime/blob/aedf8f52006619ef5d4eca65d79f42cc4b7bc402/src/coreclr/src/System.Private.CoreLib/src/System/Threading/Thread.CoreCLR.cs#L502)
That causes non-determinism in generated code in methods
inlining System.Threading.Thread.GetCurrentProcessorId()
(https://github.com/dotnet/runtime/blob/aedf8f52006619ef5d4eca65d79f42cc4b7bc402/src/coreclr/src/System.Private.CoreLib/src/System/Threading/Thread.CoreCL …

Determinism changes.

---

.gitattributes

This adds a `.gitattributes` file that mirrors the dotnet/runtime copy minus the coreclr specific section at the end.
The primary need for this is so that bash and batch files are usable regardless of how the files were checked out.

Adding a .gitattributes file that mirrors the dotnet/runtime copy

---

src/jit-format/jit-format.cs

`formatOk` wasn't updated in a thread-safe way, which resulted in errors
occasionally not being reported from formatting jobs.
Fixes https://github.com/dotnet/runtime/issues/34336

Fix the loop calling clang-tidy.

---

src/jit-format/jit-format.cs

This is the last change needed to remove the build.cmd/build.sh CoreCLR scripts in dotnet/runtime.

Make jit-format use build-runtime scripts instead of build scripts.

---

azure-pipelines.yml

Azure Pipelines removed support for macOS 10.13 so we need
to update azure-pipelines.yml to macOS 10.15.

Update macOS version.

---

src/jit-dasm-pmi/jit-dasm-pmi.cs
src/jit-dasm/jit-dasm.cs
src/jit-diff/diff.cs
src/jit-diff/jit-diff.cs

Add --nodiffable to jit-dasm, jit-dasm-pmi, jit-diff.
This is useful for using these tools to generate disassembly
to examine, not to diff.
Also, add some more output if "dotnet --info" doesn't work
as expected.

Add --nodiffable option

---

src/AnalyzeAsm/AnalyzeAsm.csproj
src/AnalyzeAsm/OccuranceInfo.cs
src/AnalyzeAsm/Program.cs
src/AnalyzeAsm/README.md

* Added following analyzer:
*  FindPreIndexAddrMode
* Find ldr followed by str or vice-versa
* Added ability to find assembly method in output produced by jit-analyze. It creates a `.index` file containing method names along with start/end line of that method in all the files. Subsequent lookups are quick. Again the folder paths are hardcoded but can be easily made to be passed via command line.

AnalyzeAsm analysis and print assembly

---

src/pmi/pmi.cs

I added a workaround for disassembly non-determinism in #255.
See #255 for details of what causes the non-determinism.
It turns out it relied on a reflection hole that allowed
init-only static fields to be modified after static constructor has
been called. That hole was fixed in https://github.com/dotnet/runtime/pull/37849
so the workaround is no longer valid and causes an exception from pmi.
I don't see a way to work around the non-determinism without changing
framework code so for now I'm just reverting the workaround. Unfortunately, that
means that we can get non-deterministic disassembly for any method that inlines
System.Threading.Thread.GetCurrentProcessorId.
Fixes #271.

Undo a non-determinism workaround.

---

src/AnalyzeAsm/Program.cs

Find addresses of adrp+add that are CSE candidates.

Add CSEForAdrpAddAddresses to AnalyzeAsm

---

src/jit-format/jit-format.cs

Currently without the OS option, jit-format does not autodetects the platform but instead produces the following error:
```sh
error: Specify --arch, --plaform, and --build for clang-tidy run.
```
if we follow the instruction from error message, it gives:
```sh
error: invalid option --plaform
error: invalid option --platform
```
The actual option it is looking for is `--os`.
Also fixed the OS name in example for Linux portable builds, which is default flavor in `dotnet/runtime`.

Fix error message in jit-format

---

src/jit-analyze/jit-analyze.cs
src/jit-diff/jit-diff.cs

Adds "Instruction Count" metrics in `jit-analyze` and `jit-diff`
Update: Also includes Variable debug info metrics from #281
Fixes #266

Add instruction count, variable debug info metrics

---

NuGet.Config
src/packages/packages.csproj
src/target-framework.props

Resolves #189
@AndyAyersMS this work now?

Add aspnet to baseline

---

doc/diffs.md
src/jit-dasm-pmi/jit-dasm-pmi.cs
src/jit-dasm/jit-dasm.cs
src/jit-diff/jit-diff.cs

Now that we have stopped producing `protononjit.dll` in https://github.com/dotnet/runtime/pull/41126, replace its reference with new name e.g. `clrjit_win_arm64_x64.dll`

Rename protononjit.dll to clrjit_win_arm64_x64.dll

---

src/jit-analyze/jit-analyze.cs

We get a weird error if a .dasm file exist in one folder and not the other. So I decided to just use `--diff-filter` option to only diff files that are present in both folders.
I thought of updating the regex, but this one seemed more compelling. 
Fixes: https://github.com/dotnet/jitutils/issues/149

Use diff-filter to filter files that are not present in both base/diff

---

src/jit-dasm-pmi/jit-dasm-pmi.cs

Fixes jit asserts when running jit-diffs --pmi for arm64 altjit.
PTAL @dotnet/jit-contrib

Fix PMI diffs for arm64 with the recent altjit renaming.

---

src/cijobs/cijobs.cs
src/jit-analyze/jit-analyze.cs
src/jit-dasm-pmi/jit-dasm-pmi.cs
src/jit-dasm/jit-dasm.cs
src/jit-diff/diff.cs
src/jit-diff/install.cs
src/jit-diff/jit-diff.cs
src/jit-diff/uninstall.cs
src/jit-format/jit-format.cs
src/jit-include.props
src/util/util.cs

- Replaced `Dotnet.Cli.Utils.Command` with `System.Diagnostic.Process` which is more robust and allow us to better handle process spawning mechanism.
- Print the `git diff` command to fix #92 
- Switch to `System.Diagnostic.Process` to fix #175.
- Add cancellation mechanism that will kill all the process and child process the given jitutil has spawned. Fixes #151 .
- Print the environment variables that fixes #141.

Replace Dotnet.Cli.Utils.Command with System.Diagnostic.Process

---

build-coredistools.cmd
build-coredistools.sh
src/coredistools/coredistools.cpp

This adds support for proper recognition of movw/movt instructions pairs on Arm in `CorAsmDiff::nearDiff`.
In a case when such instructions pairs are compared, their immediates should not be compared independently. Instead their values should be used to reconstruct a 32-bit value that is loaded into a register and these reconstructed value should be compared either for identity or equality (with a user defined `Comparator`). 
I tested this approach by 
1. **superpmi collect** on on windows-arm on framework libraries
2. **superpmi replay** on windows-arm 
3. **superpmi replay** on windows-x86 (with clrjit_win_arm_x86.dll jit)
In both 2 and 3 there were no cases of false positives diffs between baseline and compared jits. (If this algorithm is disabled, almost every method becomes different …

CoreDisTools on Arm

---

src/coredistools/coredistools.cpp

The small change is to enable additional Arm64 ISAs in the dissassembler. 
Without this change, for example, the superpmi would not be able to dissassemble a method containing `AESD` instruction.

CoreDisTools on Arm64

---

build-coredistools.cmd
build-coredistools.sh
coredistools.yml

Change the target architectures matrix for coredistools:
- win-x86, win-x64, linux-x64, osx-x64 supports X86, ARM and AArch64.
- win-arm, win-arm64, linux-arm, linux-arm64 supports ARM and AArch64.
With this change x86/x64 R2RDump can target all the platforms with one version of coredistools binaries.
I was not sure if is useful to enable X86 target support on Arm/Arm64 hosted coredistools, so I decided not to in order to have smaller coredistools binaries on these platforms.

Allow more supported target architectures for R2RDump

---

src/jit-dasm-pmi/jit-dasm-pmi.cs
src/jit-dasm/jit-dasm.cs
src/jit-diff/diff.cs

- There was miscalculation happening if the `CORE_ROOT` ended with trailing `\`. Fixed it.
- Also, in https://github.com/dotnet/jitutils/pull/287, I changed the way log files were created. If there is no contents to dump, then we would skip creating the log files. However, I missed the check if we decide to move a log file. 
Fixes: #300

Fix path problems so we can get diff working

---

src/jit-format/jit-format.cs

jit-format was broken on Windows after https://github.com/dotnet/runtime/pull/43651 was merged. Fixed it to use `Windows` instead of `Windows_NT`. This will break for people who still haven't merged the changes for `Windows_NT` -> `Windows`, but it is OK to break them because eventually using `Windows` is the right thing.

Fix jit-format for Windows

---

src/jit-analyze/jit-analyze.cs

We occasionally see warnings with `jit-analyze`:
```cmd
Couldn't parse output '182160   0       E:/lsra/binaries/EhWriteThru/bugfix/{dasmset_5/diff => dasmset_2/base}/System.Web.HttpUtility.log'.
Couldn't parse output '182160   0       E:/lsra/binaries/EhWriteThru/bugfix/{dasmset_5/diff => dasmset_2/base}/System.Web.log'.
```
They come depending on where `git diff` command was ran. I could see that the output of `git diff` was different depending on where `git diff` is ran, I am not sure why. Here is an example:
```cmd
D:\git\runtime>git diff --no-index --diff-filter=M --exit-code --numstat -- E:\lsra\binaries\EhWriteThru\bugfix\dasmset_5\tempd E:\lsra\binaries\EhWriteThru\bugfix\dasmset_2\tempb
34      51      "E:\\lsra\\binaries\\EhWriteThru\\bugfix\\dasmset_5\\tempd/CommandLine.dasm" …
```

Fix regex that parses git diff

---

src/jit-analyze/jit-analyze.cs

While working on #305 , I realized that we do "git diff" only to check if there are any files that has textual diff and no metric diff. This was added to not do the analysis of metric diff if there are no real diffs in base/diff. However, common case is that there are diffs that users analyze using `jit-analyze`. It is very rare scenario where there would be no diffs. Additionally, the code that was added to perform "git diff" so we can skip the actual analysis was broken until now and was fixed recently in #305. So far, we always did the analysis of base/diff regardless of "git diff" told that there were diffs or not. So overall, I do not find doing "git diff" in the beginning much useful and it consumes 20~30 seconds to complete. More common cases (where there are diffs), we start the …

Optimize jit-analyze

---

src/jit-format/jit-format.cs

As discussed about two weeks back in context of
https://github.com/dotnet/jitutils/pull/304
this change complements the runtime repo PR
https://github.com/dotnet/runtime/pull/44973
by fixing the correlated code in jitutils dealing with coreclr paths.
Thanks
Tomas

Counterpart fix for #44973 - remove extra "src" folder level

---

NuGet.Config

Found in response to dotnet/core-eng#11839. dotnet.myget.org was recently shut down, and these references were missed. 
It appears most references weren't used at all (or packages retrieved from other feeds). The dotnet-corefxlab feed was providing system.commandline.0.1.0-e170320-1, which is now found on the myget-legacy feed. 
Tested locally by running build.cmd to completion.

Remove MyGet references, add legacy feed

---

src/jit-analyze/jit-analyze.cs
src/jit-diff/jit-diff.cs

In https://github.com/dotnet/runtime/pull/44370 , I added way to output the allocation size in the disasm. Use that to compare the allocation size. I have also added `ExtraAllocBytes` metric that will be used to diff (alloc size - code size) and in ideal cases it should be 0.

Add AllocSize and ExtraAllocBytes metric in jit-analyze

---

src/jit-analyze/jit-analyze.cs
src/jit-diff/jit-diff.cs

I was tired of gathering the diff data for individual metric by invoking `jit-analyze` multiple times, so I went ahead and added ability to specify multiple metrics in comma-separated form so we can see the diffs of multiple metrics at one instead of invoking `jit-analyze` multiple times. Another motivation was that I wanted to output the diff result in `.md` file so I can just copy the contents from it and paste it on GH. So I went ahead and added an option of `--md` that will output the diff result (of all the metrics specified) in an `.md ` file.
Example of what you end up getting in `.md` can be seen in https://github.com/dotnet/runtime/pull/47307#issuecomment-765046091.
Contributes to https://github.com/dotnet/jitutils/issues/125

Enable jit-analyze to take multiple metrics as input and add an option to output .md file

---

src/jit-diff/diff.cs

`jit-diff diff` executes `jit-analyze` after running the diffs and always fail with `error: invalid option --metric`
I guess it was introduced in https://github.com/dotnet/jitutils/pull/312

Fix "error: invalid option --metric" error

---

src/pmi/pmi.cs

Makes `--pmi` 7% slower.
@AndyAyersMS did you mean to file a PR like this in https://github.com/dotnet/runtime/pull/48161#issuecomment-777627105 or just to test locally?

Add Nullable<int> to pmi

---

src/jit-analyze/jit-analyze.cs

Benchmarks are living dasm in subfolders, like: `dasmset_153\base\Roslyn\CscBench`, but `parsedDiffDir` was not expecting it so it was producing a bunch of errors like:
```
Error parsing path 'D:/Sergey/diffs/dasmset_159/base/BenchmarksGame/k-nucleotide/k-nucleotide-1/k-nucleotide-1.dasm'. `D:\Sergey\diffs\dasmset_159\base\BenchmarksGame\k-nucleotide\k-nucleotide-1` and `D:\Sergey\diffs\dasmset_159\base` don't match.
Error parsing path 'D:/Sergey/diffs/dasmset_159/diff/BenchmarksGame/k-nucleotide/k-nucleotide-1/k-nucleotide-1.dasm'. `D:\Sergey\diffs\dasmset_159\diff\BenchmarksGame\k-nucleotide\k-nucleotide-1` and `D:\Sergey\diffs\dasmset_159\diff` don't match.
Error parsing path 'D:/Sergey/diffs/dasmset_159/base/BenchmarksGame/pidigits/pidigits-3/pidigits-3.dasm'. …
```

Delete "Error parsing path " messages when comparing benchmarks

---

src/target-framework.props

Explicitly use the oldest* available LTS framework as the TargetFramework. This will more easily allow using tools like PMI with both a 3.1 runtime and a 5.0 runtime.

Explicitly use the oldest* available LTS framework

---

src/jit-format/jit-format.cs

Required for https://github.com/dotnet/runtime/pull/49715
cc: @dotnet/jit-contrib for review.

Support the nmakeobj path and the standard intermediate output path for compile_commands.json on Windows.

---

src/jit-analyze/jit-analyze.cs

Minor PR to not show headers if `-c 0` passed to `jit-analyze`. I am trying to get just the overall % diffs and not interested in individual file diffs.

Skip printing headers if count==0

---

src/pmi/PMIDriver.cs
src/pmi/pmi.cs

This simply logs the environment variables that are set as part of the invoked command and failures information to allow easier debugging and investigation into failures.
```
DRIVEALL: Invoking D:\Users\tagoo\Source\repos\runtime_base\artifacts\tests\coreclr\windows.x64.Release\Tests\Core_Root\corerun.exe C:\Users\tagoo\Source\repos\jitutils\bin\pmi.dll PREPALL-QUIET D:\Users\tagoo\Source\repos\runtime_base\artifacts\tests\coreclr\windows.x64.Release\Tests\Core_Root\System.Private.CoreLib.dll 0
DllNotFoundException Interop+HostPolicy::corehost_resolve_component_dependencies (Unable to load DLL 'hostpolicy.dll' or one of its dependencies: The specified module could not be found. (0x8007007E))
DllNotFoundException Interop+HostPolicy::corehost_set_error_writer (Unable to load DLL …
```

Log the environment variables and failures that occur as part of DRIVEALL

---

src/AnalyzeAsm/Program.cs

Added `FindRedundantTest()` method that looks for redundant `test` instruction in the dasm files. I have scoped it to limited jump instructions, but can be extended in the future. Used in https://github.com/dotnet/runtime/issues/53053.

Add FindRedundantTest() in AnalyzeAsm

---

bootstrap.cmd
src/jit-analyze/jit-analyze.cs

Often times, metric delta of one huge method hides the improvements of other smaller methods. Introduce `relative delta` that will calculate `(diff - base) / base` for individual method and then sum the result to display in the summary.
Sample output:
```
Summary of Perf Score diffs:
(Lower is better)
Total PerfScoreUnits of base: 173075468521.34006
Total PerfScoreUnits of diff: 172839103599.6798
Total PerfScoreUnits of delta: -236364921.66 (-0.14% of base)
Total relative delta: 0.13
diff is an improvement.
relative diff is a regression.
```
Also, it turned out that we were recalculating `deltaMetrics` without caching. I introduced private `_deltaMetrics` that will cache the result instead of recomputing.
Lastly, added some `ToString()` methods to get better debugging visualization.

Introduce relative score metric in jit-analyze

---

src/jit-analyze/jit-analyze.cs

Parse LSRA stats from dasm files. I have just included `Spill` and `ResolutionMov` related stats and will add more if and when needed.
Related change: https://github.com/dotnet/runtime/pull/53901

Include few LSRA stats diff

---

src/jit-analyze/jit-analyze.cs

I am using meld to compare different jit-analyze outputs and sometimes I see diffs like:
```diff
-           4 (10.00% of base) : 116814.dasm - System.Data.SqlTypes.SqlDecimal:ToSqlSingle():System.Data.SqlTypes.SqlSingle:this
-           4 (10.00% of base) : 116807.dasm - System.Data.SqlTypes.SqlDecimal:ToSqlBoolean():System.Data.SqlTypes.SqlBoolean:this
4 (10.00% of base) : 116811.dasm - System.Data.SqlTypes.SqlDecimal:ToSqlInt32():System.Data.SqlTypes.SqlInt32:this
+           4 (10.00% of base) : 116807.dasm - System.Data.SqlTypes.SqlDecimal:ToSqlBoolean():System.Data.SqlTypes.SqlBoolean:this
+           4 (10.00% of base) : 116814.dasm - System.Data.SqlTypes.SqlDecimal:ToSqlSingle():System.Data.SqlTypes.SqlSingle:this
```
that I would like to avoid.
PTAL @dotnet/jit-contrib

Add sorting by name to "Top method regressions/improvements"

---

src/jit-dasm/jit-dasm.cs

with parallelism on, crossgen outputs some abracadabra for JitDisasm (methods overlap)

Disable parallelism for crossgen2

---

bootstrap.sh

Add retry logic during downloading clang tools in unix. Turns out we only added retry logic for windows in https://github.com/dotnet/jitutils/pull/327/files and not for linux.

use retry for downloading clang tools

---

bootstrap.sh

Chances of having curl on a fresh Linux / macOS install are actually higher than having wget, but even if there is a tie, using available tool in PATH which does the job right is good. This is the only script related to runtime that force the user to install wget.
.. was about to run `brew install wget` then thought I should do this first. 😄

Recognize curl as a downloading tool

---

azure-pipelines.yml
bootstrap.sh

ubuntu-16.04 was removed recently (https://github.com/actions/virtual-environments/issues/3287), bumping to 20.04
win2016 will be removed in March: https://github.com/actions/virtual-environments/issues/4312, bumping to windows-2019

Use non-deprecated Azure Pipelines Ubuntu/Windows pool

---

src/util/util.cs

For example, if running `jit-analyze` but `git` is not on the path,
print a more useful error than an exception stack trace.

Catch exceptions if spawning a process fails

---

src/jit-analyze/jit-analyze.cs

`RetainBigDiffFilesOnly` will make `jit-analyze` to delete the `.dasm` files and retain just the top `count` files that contains largest diffs. This will help us in reducing the `.dasm` files size when we upload them as part of CI. By default, this option is off and hence we will never delete those files.
Thoughts?

Add option of retainOnlyTopFiles to jit-analyze

---

coredistools.yml
src/coredistools/.nuget/Microsoft.NETCore.CoreDisTools.nuspec

Update the Linux jobs to use ubuntu-18.04 pool and also update the Docker containers to use the latest images.

Update coredistools infrastructure dependencies

---

build-coredistools.cmd
build-coredistools.sh
coredistools.yml
eng/download-llvm-release.py
src/coredistools/.nuget/Microsoft.NETCore.CoreDisTools.nuspec
src/coredistools/CMakeLists.txt
src/coredistools/coredistools.cpp

Summary of the changes:
* Updated coredistools.cpp to work with LLVM 13
* Removed win-arm coredistools library (dotnet/runtime doesn't officially support this target anymore and there was an issue building the newer version of LLVM for that platform)
* Added osx-arm64 coredistools library
* Removed AArch64 disassembler from win-x86 and linux-arm coredistools libraries (there are no corresponding JITs anyway)
* Added X86 disassembler to linux-arm64 and win-arm64 (so these platforms can be used for the JIT development)
* Updated relevant pipeline files
* Updated NuGet package version to 1.1.0
It is now possible to collect superpmi asmdiffs on Apple M1:
```
Using JIT/EE Version from jiteeversionguid.h: 1d61ee87-b3be-48ae-a12e-2fb9b5b1cee7
Using coredistools found at …
```

Update coredistools to use LLVM 13.0.0 and build coredistools for macOS arm64 

---

build-coredistools.cmd
build-tblgen.cmd
coredistools.yml
eng/download-llvm-release.py

* Use LLVM 13.0.1
* Use Visual Studio 2022 for building on Windows
* Use Ubuntu 18.04 containers for building on Linux
Work towards https://github.com/dotnet/jitutils/issues/349

Update LLVM version to 13.0.1

---

doc/building-coredistools.md

Update to account for https://github.com/dotnet/jitutils/pull/351

Update coredistools documentation

---

src/jit-analyze/jit-analyze.cs

It is confusing for jit-analyze to display this summary when invoked through SPMI since SPMI will only create .dasm files for some contexts. Add some options to control the summary written.

Add --is-diffs-only and --is-subset-of-diffs

---

doc/formatting.md

I noticed that the python script changed its name, and the example command line arguments are out of date.

Fix formatting instructions using the python script to match current runtime repo behavior

---

NuGet.Config

We are still depending on an ancient version of System.Commandline, 0.1.0-e170320-1, which we get from this feed. Readd it to unblock things, otherwise all our SPMI jobs fail in dotnet/runtime when they try to build jitutils.

Readd myget-legacy feed

---

src/jit-dasm/jit-dasm.cs

* Update references Ngen environment variables
* crossgen2 was invoked with --outputfilepath, but the actual command line arg is --out. This was apparently not an error until recent crossgen2 parser changes.

Fix jit-diff with crossgen2

---

build-coredistools.sh
src/coredistools/coredistools.cpp
src/coredistools/coredistools.h

LoongArch64: initial the coredistools supporting LA64.

LoongArch64: initial the coredistools supporting LA64.

---

src/jit-format/jit-format.cs

Fixes https://github.com/dotnet/runtime/issues/84780. Tested by hooking up the changes locally with runtime's `jitformat.py` and running `python3 ./src/coreclr/scripts/jitformat.py -c /runtime/src/coreclr -o linux -a x64` in our mariner build container.
This might break scenarios where jitutils are used outside of ci on a non-mariner build image. Per discussion with @BruceForstall let's make a quick fix to unblock ci, and if this is problematic we could for example add an extra argument that controls whether the `-cross` argument is passed to the runtime build.
For context, the `-cross` argument is necessary after https://github.com/dotnet/runtime/pull/84148 because our linux build images have change from centos 7 to CBL-mariner, and the linux builds are now cross-builds that use a rootfs …

Pass "-cross" arg on linux builds

---

src/jit-analyze/Program.cs

The documentation says that passing jit-analyze two file paths instead of directories is supported, but the code did not know which two files to compare in the case where they had different names.
Example. Before:
```powershell
❯ jit-analyze --base "C:\dev\dotnet\perf-diff-finder\results\System.Tests.Perf_String.CtorCharCount(size__100)\base.dasm" --diff "C:\dev\dotnet\perf-diff-finder\results\System.Tests.Perf_String.CtorCharCount(size__100)\diff.dasm" --warn
Found 1 files with textual diffs.
Summary of Code Size diffs:
(Lower is better)
Warning: the base metric is 0, the diff metric is 0, have you used a release version?
0 total files with Code Size differences (0 improved, 0 regressed), 0 unchanged.
0 total methods with Code Size differences (0 improved, 0 regressed), 0 unchanged. …
```

Support jit-analyze being explicitly passed single files of different names

---

src/pmi/pmi.cs

I frequently hit "The process cannot access the file" errors when PMI tries to write the marker file, presumably due to AV software locking this file. This adds a retry loop to try writing the marker a few times before aborting.

Add a retry loop in WriteAndFlushNextMethodToPrepMarker

---

bootstrap.cmd
bootstrap.sh
doc/cijobs.md
doc/formatting.md
src/cijobs/CIJobsRootCommand.cs
src/mutate-test/Program.cs

- Use https: instead of http: where the remote server honors https (basically, every place that's not an XML namespace URI)
- Remove stale references to dotnet-ci.cloudapp.net

Fixup URLs in comments and docs

---

src/jit-format/jit-format.cs

Add a `--cross` argument for specifying to do cross compilation builds on Linux.
Replace the `--coreclr` argument with `--runtime`, to specify the root of the runtime repo.
Fix a minor bug where we output a lot of empty lines doing clang-tidy.

Add `--cross` arg; replace `--coreclr` with `--runtime`

---

src/instructions-retired-explorer/instructions-retired-explorer.cs
src/instructions-retired-explorer/instructions-retired-explorer.csproj

Fix instructions retired explorer to understand new categories of jitted code introduced in .NET 8.
Use proper event field rather than trying to decode flags.
Update trace event to a version with the new OptimizationTier values.

Update for new categories of tiered compilation

---

build-coredistools.sh
build-tblgen.sh
doc/building-coredistools.md
src/coredistools/coredistools.cpp
src/coredistools/coredistools.h

Needed for R2RDump --disasm
Part of dotnet/runtime#84834
cc @wscho77 @HJLeee @clamp03 @JongHeonChoi @t-mustafin @gbalykov @viewizard @ashaurtaev @brucehoult @sirntar @yurai007 @bajtazar

[RISC-V] Build coredistools

---

src/jit-rl-cse/MLCSE.cs
src/jit-rl-cse/MLCSE.csproj

Add a tool that can use ML techniques to explore the JIT's CSE heuristic. Some parts of this are very specific to CSEs, others are general and could be repurposed for use with other heuristics.
This is still work in progress.
Depends on jit changes in dotnet/runtime#96880

Initial version of a tool for ML on CSEs

---

src/jit-rl-cse/MLCSE.cs

Parsing was broken when I added the initial `; ` to the metrics line. Fix this.
Also fix MCMC forgetting mode, so you can first run MCMC to explore the range of possible CSEs, then try Policy Gradient to see if it can come close to this.

Fix RLCSE for new metrics format

---

src/jit-diff/jit-diff.cs

Running `jit-diff` from the runtime root can fail due to the existence of the `globa.json` and custom SDK that is setup since the `Platform` line may not be printed in that scenario.
This adds some basic fallback logic to ensure we can still work in that scenario.

Adding a fallback for the platform if it couldn't be detected from dotnet --info

---

src/jit-analyze/JitAnalyzeRootCommand.cs
src/jit-analyze/Program.cs

Specifying this option makes jit-analyze concatenate all files in the input base/diff directories and treat them as a single logical unit.
Example: To produce all .dasm files for a change (instead of just some hand picked example ones), one can pass `-metrics CodeSize` to `superpmi.py`: `superpmi.py asmdiffs -metrics CodeSize`
This creates base/diff directories with a single .dasm file for every code size difference. Running `jit-analyze --base <path to base dir> --diff <path to diff dir>` gives
```scala
Found 3820 files with textual diffs.
Summary of Code Size diffs:
(Lower is better)
Total bytes of base: 4017093
Total bytes of diff: 4067605
Total bytes of delta: 50512 (1.26 % of base)
Total relative delta: 72.45
diff is a regression.
relative diff is a regression.
Top file regressions …
```

Add --concat-files option to jit-analyze

---

src/jit-rl-cse/MLCSE.cs
src/jit-rl-cse/MLCSECommands.cs

The JIT will append dumps to existing files, so using RLCSE to save dumps was creating large files (each sequence's dump is periodically updated to show the impact of the current parameters).
Also I was going to make MCMC and such subcommands, but changed my mind, and forgot to hook the options back up.

RLCSE: fix MCMC and GatherFeatures, overwrite dumps

---

src/jit-rl-cse/MLCSE.cs
src/jit-rl-cse/MLCSECommands.cs

Add support to use streaming SPMI servers. When enabled, RLCSE will launch one SPMI server process per core. Work dispatched to servers picks an idle server from the pool of servers. This greatly reduces the overhead of doing single-method evaluations.
SPMI streaming mode requires the changes in dotnet/runtime#98440.
Update the main Policy graident work loop and the greedy status loop to use the streaming mode, if enabled. MCMC can leverage this too, but I haven't done that just yet.
Add the ability to track server status.
Add the ability to log the server activity. The intent is that these logs can be replayed by a server instance to diagnose problems. This was useful during bring-up.
Add a running log of the Policy Gradient parameter values, so we can see how they change over time. …

RLCSE: streaming SPMI mode

---

src/coredistools/coredistools.cpp

Without them only instructions from "I" base extension were recognized in disassembly.
Part of dotnet/runtime#84834
cc @wscho77 @HJLeee @clamp03 @JongHeonChoi @t-mustafin @gbalykov @viewizard @ashaurtaev @brucehoult @sirntar @yurai007 @Bajtazar @bartlomiejko @rzsc

[RISC-V] Add LLVM subarch features for RISC-V GC

---

src/jit-rl-cse/MLCSE.cs
src/jit-rl-cse/MLCSECommands.cs

Add a new `--optimizeSize` option where PolicyGradient tries to reduce code size instead of perf score.
Since there are now two possible optimization objectives, we have the potential for trading off one for the other.  Update MCMC to track the "pareto frontier" for the methods it explores and save the data for visualization.
Contributes to dotnet/runtime#92915.

MLCSE: lay groundwork for optimizing for size

---

bootstrap.cmd
bootstrap.sh
eng/build.yml
src/jit-format/jit-format.cs

These are now uploaded in a new location in JIT Azure Storage for three platforms currently:
- windows-x64
- linux-x64
- osx-arm64
So jit-format will work on any of these platforms now.
Note that osx-x64 is no longer supported for clang-format/clang-tidy.
This includes https://github.com/dotnet/jitutils/pull/407.

Use clang-format/clang-tidy version 17.0.6

---

src/coredistools/coredistools.cpp

Add extensions of ratified RISC-V application profiles (the unprivileged side). JIT doesn't emit code for newly added extensions yet, this is to future-proof since coredistools are rebuilt infrequently. See https://github.com/dotnet/jitutils/issues/414#issuecomment-2358303120 for context.
Part of dotnet/runtime#84834, cc @dotnet/samsung @BruceForstall

[RISC-V] Add RVA profiles to coredistools

---

src/coredistools/.nuget/Microsoft.NETCore.CoreDisTools.nuspec

To pick up recent build changes enabling /guard:cf.

Bump coredistools version to 1.6

---

src/instructions-retired-explorer/instructions-retired-explorer.cs

We no longer get method load events for R2R methods, but there are events that are fired when the runtime goes to find an R2R entry point that are almost as good. Enable these via `-RuntimeLoading` command line arg to perfview.
Add support for parsing these events and inferring the length of R2R methods from them.

Add updated R2R analysis
