- README.md
Add code of conduct statement and links to the project README.md
> Add MSOpen code of conduct statement

- doc/getstarted.md
Specify the `--frameworksonly` option that was missing in that section.
Also apply some minor formatting tweaks.
> Update getstarted doc

- src/jit-diff/jit-diff.cs
Privious change broke this functionality.
> Fix IO capture for calculating RID.

- src/jit-diff/jit-diff.cs
This makes it trivial to check diffs specifically on the benchstone and
benchmark game benchmarks.
> Add --benchmarksonly flag

- src/jit-analyze/jit-analyze.cs
Closes #10.
Extend jit-analyze to display the total and file diff sizes as
percentages of the base size. File diffs show percent change in
that file.
Also, enable reconciliation by default.
Sample output:
```
Total bytes of diff: -96445 (-1.13 % of base)
diff is an improvement.
Total byte diff includes 4771 bytes from reconciling methods
Base had   54 unique methods,     8864 unique bytes
Diff had  168 unique methods,    13635 unique bytes
Top file regressions by size (bytes):
26840 : Microsoft.CodeAnalysis.dasm (3.60 % of base)
19283 : System.Xml.ReaderWriter.dasm (3.36 % of base)
9955 : System.Text.RegularExpressions.dasm (10.78 % of base)
572 : System.Xml.XDocument.dasm (0.73 % of base)
549 : System.Runtime.Extensions.dasm (1.29 % of base)
```
> Add percentages to jit-analyze; enable reconcilation

- src/jit-format/jit-format.cs
If the user did not specify a compile_commands.json, but one exists, we
will default to using it. This is to allow the use of
compile_commands.json files that were generated by cmake with NMake
Makefiles on Windows. These files require slightly more processing than
cmake files generated by cmake on non-windows platforms, as clang gets
confused by some of the windows specific flags, and we also have to force
the use of various other flags.
This change also modifies the output of DoClangFormat so that the output
doesn't get interleaved during the parallel runs of clang-format. We write
all the output to a list, and then print it out after we have run all
clang-format instances.
> Rewrite compile commands on Windows

- bootstrap.sh
> Fix function in bootstrap

- bootstrap.sh
This reverts commit 7ed1c6956145cd2ff9a00b31accf60d517079cbb.
> Revert "Add interpretter to top of bootstrap.sh"

- bootstrap.cmd
After this there are two "modes": 1. invoke bootstrap.cmd from an existing clone, or 2. invoke it from a downloaded copy. With 1, it just builds everything (and downloads clang-format/clang-tidy, if necessary).
@adiaaida @russellhadley PTAL
> Allow bootstrap.cmd to be used for building without doing a clone

- src/jit-format/jit-format.cs
When clang-format reports that there are formatting errors, rather than
printing that the user should rerun in fix mode, give a more explicit
command line.
Additionally, print the first 10 formatting errors when not in verbose
mode.
> Change output for clang-format

- src/cijobs/cijobs.cs
This change adds options to the list and copy commands that allow
retrieving the information or artifacts for a specific commit, and
removes compiler warnings about unused variables and uninitialized
fields that are only set by json deserialization.
> Add support to cijobs for retrieving builds by commit

- src/jit-analyze/jit-analyze.cs
In the jit-analyze summary, print the raw numbers of files/methods that
improved/regressed.  i.e., add the bit in parentheses to these lines in
the summary:
93 total files with size differences (17 improved, 76 regressed).
3478 total methods with size differences (1315 improved, 2163 regressed).
> Add improved/regressed to file/method counts

- src/jit-diff/jit-diff.cs
The code that deals with running jit-dasm for base and diff is pretty much the same.
Also fix `commandArgs` copying, the old code was making a reference copy so the diff jit-dasm ended up with a command line containing duplicated `--tag` options:
> jit-dasm --platform D:\Projects\jitutils\fx\ --output D:\Projects\diffs\dasmset_13 --tag base --crossgen D:\Projects\coreclr\bin\Product\Windows_NT.x64.Checked_base\crossgen.exe --tag diff --crossgen D:\Projects\coreclr\bin\Product\Windows_NT.x64.Checked\crossgen.exe D:\Projects\jitutils\fx\System.Console.dll
> Remove duplicated code from jit-diff

- jitutils.sln
- src/cijobs/cijobs.csproj
- src/jit-analyze/jit-analyze.csproj
- src/jit-dasm/jit-dasm.csproj
- src/jit-diff/jit-diff.csproj
- src/jit-format/jit-format.csproj
- src/packages/packages.csproj
There is some magic here that allows VS2017 to allow better
debugging, e.g., setting of command-line arguments.
> Reconstruct sln/csproj files in VS2017

- src/jit-analyze/jit-analyze.cs
This gives a bit more context for the improved/regressed counts.
Resolves #81, resolves #83.
> Jit-Analyze: Display unchanged file/method counts

- doc/diffs.md
- src/jit-dasm/jit-dasm.cs
- src/jit-diff/diff.cs
- src/jit-diff/jit-diff.cs
e.g., `jit-diff --altjit protononjit.dll ...`
> Add support for generating asm diffs using an altjit

- src/pmi/PMI.csproj
- src/pmi/PMIDriver.cs
- src/pmi/pmi.cs
- src/pmi/readme.md
This is the desktop version with just a few cleanup changes here and there.
It is set up to dual-target netcoreapp2.1 (which is the minimum core version that is viable) as well as net45. Probably not fully functional on core yet, though prepall works for many assemblies.
> Initial commit of PMI sources

- src/pmi/PMIDriver.cs
Details of creating a cloned process are a bit different for the CLI.
Handle this via condtionally compiled code for now.
Still other changes would be required to support mixing the "host" and
target runtimes. It might be worth explicitly specifying these somehow.
Also did some folding of long lines.
> PMI: fix DRIVEALL for use with dotnet cli

- src/pmi/pmi.cs
Previous changes removed the bit of code to actually install the
assembly resolve handler.
Also, lay ground work for being able to re-use a visitor to visit
multiple assemblies.
> PMI: Hook up assembly resolve handler

- src/pmi/pmi.cs
Start keeping tabs on assemblies that won't load, types that can't
be instantiated, and methods that can't be instantiated.
Note this does not track methods that fail to jit. Need to think
about that some more.
Add provisional support for running PMI on all the assemblies in a
directory tree (core only for now). Report aggregate stats if we end
up PMIing multiple assemblies.
Convert remaining formatting in pmi.cs to interpolated style.
> PMI: start keeping track of missing and failing things

- src/jit-diff/diff.cs
We should always be copying/restoring via the test jit name.
> Fix pmi so it works properly with --altjit

- src/jit-analyze/jit-analyze.cs
Start working towards highlighting files where codegen (potentially) differs
but the overall method size stays the same.
In this initial version jit-analyze will list the top N files files that have
zero size diffs but have some text diff, ordered by decreasing number of diff
lines.
N here is controlled by the --count parameter like the other "top N" sections
of the diff summary and defaults to 5.
Users can then manually inspect diffs in those files to see what, if any, code
has changed in the methods in the file.
> jit-analyze: show top N files with text diffs but no size diffs

- src/pmi/pmi.cs
Fixes https://github.com/dotnet/jitutils/issues/147
> Remove some dead code causing PMI crash on b399444a.exe

- src/jit-dasm-pmi/jit-dasm-pmi.cs
- src/jit-diff/diff.cs
Set the SIMD size if the jit looks like it is cross-targeting. Currently
just checking altjits for "non".
Add simple progress bar to jit-diffs that shows up if you are running with
output to the console.
> Progress bar and SIMD size

- src/jit-dasm-pmi/jit-dasm-pmi.cs
> Add COMPlus_ZapDisable=1 to output disasm for pre-jitted methods

- src/jit-analyze/jit-analyze.cs
When analyzing a large collection of diff assemblies, you can use this to focus
analysis on a subset.
> Add filter option to jit-analyze

- azure-pipelines.yml
- eng/build.yml
This is an initial version of CI for jitutils. For now it just builds jitutils using bootstrap script for Windows_NT, Linux and macOS - no publishing yet.
> Set up CI with Azure Pipelines

- src/pmi/pmi.cs
Allows us flexibility to try and locate dependent assemblies, and also
avoid conflicts with the assemblies PMI itself is using.
> Have PMI use a custom assembly load context

- src/jit-format/jit-format.cs
rewriteCompileCommands had two bugs that were canceling each other
with VS2017: extracting cl.exe path was incorrect when it contained
spaces and constructing a new string from options could miss a space
after /FP<path> option.
VS2017 used long file names so we ended up with an extra quote after
cl.exe and that was compensating for a lack of a space after /FP<file>
option.
VS2019 uses 8.3 path for cl.exe so the compensating quote is not there
and clang-tidy complains.
This change fixes both bugs and also cleans up a couple of places:
I collapsed identical if and else code and added checking for "Error"
in addition to "error:" in command output. I noticed that clang-tidy may
fail with just "Error" in the output.
> jit-format fixes

- src/jit-analyze/jit-analyze.cs
- src/jit-diff/diff.cs
- src/jit-diff/jit-diff.cs
1.  Added -count N arg support to jit-diff
2.  Updated jit-diff  help message to print the available metrics.
3.  Added Percentage of Metric columns for the TSV files in jit-analyze
> Updates to jit-diff and jit-analyze

- src/superpmi/superpmicollect.cs
- src/superpmi/superpmicollect.csproj
This is a pristine copy to use as a starting point for PMI/SPMI mashups.
> Bring over superpmicollect from coreclr/runtime repo

- src/pmi/PMIDriver.cs
- src/pmi/pmi.cs
Get things working again with netcoreapp5_0.
* updated and generalize some of the conditional compilation symbols
* log driveall invocations
* update help text
* add handler for a common exception type
> Various pmi fixes

- src/pmi/pmi.cs
Update PMI to jit the method from dotnet/runtime#1713.
> PMI: add another async special case

- src/jit-format/jit-format.cs
The change to `--runtime` pointing to the runtime repo root
was not fully plumbed through, so if you didn't pass it explicitly
the src\coreclr directory, jit-format didn't work. (Note that the
CI jobs do pass this explicitly.)
Remove the `--runtime` argument, and verify that the `--coreclr`
directory is correct.
Added some additional logging in `verbose` mode about what command
lines are being executed.
> Revert jit-format to using --coreclr, not --runtime

- src/pmi/pmi.cs
ArrayPool<> is used in several places during the pmi execution.
In particular, ArrayPool<ReadOnlyMemory<>>.Shared.Return is called.
That method registers Gen2GcCallbackFunc on Gen2GcCallback object.
Gen2GcCallbackFunc is then called from Gen2GcCallback finalizer after
a gc. At that point Gen2GcCallbackFunc is jitted. Since gc time is not
deterministic, the disasm output for Gen2GcCallbackFunc and methods
it calls was not deterministic.
The fix is to force the registration of Gen2GcCallbackFunc and then
force a gc so that Gen2GcCallbackFunc is jitted.
> One more PMI determinism fix.

- jitutils.sln
- src/AnalyzeAsm/AnalyzeAsm.csproj
- src/AnalyzeAsm/Program.cs
- src/AnalyzeAsm/README.md
Added AnalyzeAsm project that I used to print disassembly of particular method and doing peephole analysis. The code is as-is and need lot of cleaning. I will probably do it when I have some cycles.
I haven't intentionally added it in `build.cmd` yet.
> Added AnalyzeAsm

- src/AnalyzeAsm/OccurenceInfo.cs
- src/AnalyzeAsm/Program.cs
I missed updating the spelling.
> Fixed the spelling of occurance->occurence

- src/jit-analyze/jit-analyze.cs
> Minor fixes in jit-analyze

- build-coredistools.sh
- doc/building-coredistools.md
Add initial version of documentation for building coredistools out of jitutils repository.
> Add coredistools documentation

- src/superpmi/superpmicollect.cs
Match https://github.com/dotnet/runtime/pull/44834
> Update SuperPMI scripting to match dotnet/runtime

- src/jit-format/jit-format.cs
1. Currently, if you run `jit-format` but aren't already using
ninja, it does a full ninja build of the dotnet/runtime repo.
Change the invocation of `build-runtime.cmd` to use the
`-configureonly -ninja` args instead of `usenmakemakefiles` so
only the cmake configure part of the build is run, which generates
the `compile_commands.json` that the format tool needs. After this
goes in, we can remove the obsolete `usenmakemakefiles` switch
from `build-runtime.cmd`, as it is only there to support `jit-format`.
2. `jit-format` invokes `dotnet --info` to figure out the OS. But
this doesn't work when invoking the executable dotnet (as opposed
to the script wrapper dotnet.cmd/sh) when inside the runtime repo,
as it doesn't report as much information as we want. So, for simplicity,
just invoke the …
> Improve jit-format

- bootstrap.cmd
On download failure, add 3 retries, with 15 second waits between them.
> Add download retry on failure for clang tools

- src/jit-analyze/jit-analyze.cs
This will be used by SPMI to show true totals in SPMI diffs.
Necessary for https://github.com/dotnet/runtime/pull/60124.
> Add command line args to override totals shown by jit-analyze

- build.cmd
- build.sh
This is needed on .NET 6 SDKs.
> Specify RID for self-contained publish

- src/cijobs/CIJobsRootCommand.cs
- src/cijobs/Program.cs
- src/jit-analyze/JitAnalyzeRootCommand.cs
- src/jit-analyze/Program.cs
- src/jit-dasm-pmi/JitDasmPmiRootCommand.cs
- src/jit-dasm-pmi/Program.cs
- src/jit-dasm/JitDasmRootCommand.cs
- src/jit-dasm/Program.cs
- src/jit-include.props
- src/mutate-test/MutateTestRootCommand.cs
- src/mutate-test/Program.cs
- src/util/CommandLineHelpers.cs
Other dotnet repos have recently updated command-line-api version following the breaking changes after the API review: https://github.com/dotnet/command-line-api/issues/2146. Lets bring jitutils to the same plan now, as these conversion tweaks are fresh in our muscle memory.
cc @jakobbotsch, @adamsitnik
> Update System.CommandLine version

- doc/diffs.md
- src/jit-dasm-pmi/Program.cs
- src/jit-dasm/Program.cs
`DOTNET_JitDiffableDasm` => `DOTNET_JitDisasmDiffable`
`DOTNET_JitDasmWithAlignmentBoundaries` => `DOTNET_JitDisasmWithAlignmentBoundaries`
Follow-up to [dotnet/runtime#82666](https://github.com/dotnet/runtime/pull/82666)
> Update environment variables

- src/jit-rl-cse/MLCSE.cs
- src/jit-rl-cse/MLCSE.csproj
- src/jit-rl-cse/MLCSECommands.cs
- src/util/CommandLineHelpers.cs
Change a bunch of internal settings to be configurable via the command line.
> Use System.CommandLine for MLCSE

- src/jit-rl-cse/MLCSE.cs
Also add ability to save dumps of greedy policy behavior.
> RLCSE: fixes for running on linux

- src/jit-rl-cse/MLCSE.cs
Screen out methods that were jitted with OptRepeat, their CSE metrics may not make any sense.
For streaming SPMI, increase the wait interval after each wait, as OSX seems to like to put the server processes to sleep right away.
Closes #400.
> MLCSE: fix a few issues

- src/jit-rl-cse/MLCSE.cs
Add some sanity checks that the SPMI collection and the SPMI tool are of the same vintage. It would be nice if MCHs conveyed this information directly but for typical usage we can rely in the guid being there in the file name.
Would be nice to do similar for collection Os/Arch but am not doing that yet.
Attempt to create the output dir if it does not exist.
Consistently divide by the base value when comparing against best. This means good comparison values are always less than 1, and bad one greater than one.
> RLCSE: add some validation, consistently divide by base

- src/jit-rl-cse/MLCSE.cs
- src/jit-rl-cse/MLCSECommands.cs
* Try and make the pareto frontier duplicate removal work better.
* Show evaluation and update details if requested.
* Fix MCMC best logic
> MLCSE: more small fixes

- src/jit-diff/diff.cs
Currently, jit-diff will start jit-dasm processes for all assemblies at the same time.
This change limits how many processes we start at the same time to avoid overwhelming machines with less memory available.
Main motivation is that I'm currently forced to use `--sequential` with @MihuBot when running on Azure Container Instances since they're quite resource limited.
> Limit jit-diff parallelism

- src/coredistools/coredistools.cpp
Add recently ratified RVA23 to coredistools for future implementations.
Part of dotnet/runtime#84834, cc @dotnet/samsung
> [RISC-V] Add RVA23 profile

- src/coredistools/.nuget/Microsoft.NETCore.CoreDisTools.nuspec
- src/coredistools/coredistools.h
Remove version number from header file
> Bump coredistools version to 1.5

- src/jit-analyze/JitAnalyzeRootCommand.cs
- src/jit-analyze/Program.cs
- src/jit-dasm-pmi/JitDasmPmiRootCommand.cs
- src/jit-dasm-pmi/Program.cs
- src/jit-dasm/JitDasmRootCommand.cs
- src/jit-dasm/Program.cs
- src/jit-include.props
- src/jit-tp-analyze/Program.cs
- src/util/CommandLineHelpers.cs
Sync with runtime version https://github.com/dotnet/runtime/commit/a58e9239e3dbe2259621507df51f7dcbfd849ae4.
> Update command-line-api to beta5
